Added endpoint to update a user contact
Klip-Generate/Klip-Back-End pull request #23
Opened 2021-03-03 01:55 UTC by samlowe106

2021-03-06 19:22 UTC, mattognibene commented on api/views.py
> +    user_id = request.user.id
I think it might be easier just to have the entire contact object in the body. That way, it exactly matches what you get back from the server.
So something like
`{
            "id": 18,
            "userId": 5,
            "phoneNumber": "6094125347",
            "contactName": "matt ognibene",
            "active": true
        }`

2021-03-06 19:22 UTC, mattognibene commented on api/views.py
> +        contact_item.update(**payload)
is `**payload` a spread operator or something? haven't seen it before

2021-03-11 20:53 UTC, samlowe106 commented on api/views.py
> +        contact_item.update(**payload)
Not sure, I saw it in Vab's code and assumed it was there for a reason

2021-03-11 20:59 UTC, samlowe106 commented on api/views.py
> +        contact_item.update(**payload)
I think it's to unpack dictionaries and send them as keyword arguments, as described here: https://stackoverflow.com/a/36908/15216031

Similar to how you sometimes see **kwargs when defining a function that takes an arbitrary number of keyword arguments

2021-03-12 14:06 UTC, mattognibene requested changes
Looking at this deeper, it looks like updating models in Django is way more involved than I first realized. Gonna have to look a little deeper into this

2021-03-12 14:48 UTC, mattognibene commented
I think the simplest solution might just be making the add_contact endpoint an upsert

2021-04-11 22:43 UTC, closed without merging